name: note_app
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application
version: 1.0.0+1

# Flutter SDK version
environment:
  sdk: ^3.7.2

# Dependencies required for your project
dependencies:
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter

  # Cupertino icons for iOS style icons
  cupertino_icons: ^1.0.8

# Development dependencies for testing and linting
dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/notes_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/notes_app.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/notes_app.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/notes_app.png"





  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configuration
flutter:
  # Ensure that Material Design icons are available in your app
  uses-material-design: true

  # Assets to be included in your app
  assets:
    - assets/icons/notes_app.png
    # - images/a_dot_ham.jpeg

  # Add custom fonts to your application (example)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
