// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIO2nyp4sFgeqKnm3-6lCzTHnHLWnr9yI',
    appId: '1:772902708850:web:87a97f6175fe97aae784eb',
    messagingSenderId: '772902708850',
    projectId: 'notepad-2d87a',
    authDomain: 'notepad-2d87a.firebaseapp.com',
    storageBucket: 'notepad-2d87a.firebasestorage.app',
    measurementId: 'G-HNDM70YQRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBreF3YLsvszYOyhKQodkMDEvHFrfLdIGc',
    appId: '1:772902708850:android:4b2e87750d8ae012e784eb',
    messagingSenderId: '772902708850',
    projectId: 'notepad-2d87a',
    storageBucket: 'notepad-2d87a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEAyVcEIYiBHu7_TZRQ1ZpiacRMVwL-PE',
    appId: '1:772902708850:ios:c305581d2d56ae31e784eb',
    messagingSenderId: '772902708850',
    projectId: 'notepad-2d87a',
    storageBucket: 'notepad-2d87a.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEAyVcEIYiBHu7_TZRQ1ZpiacRMVwL-PE',
    appId: '1:772902708850:ios:c305581d2d56ae31e784eb',
    messagingSenderId: '772902708850',
    projectId: 'notepad-2d87a',
    storageBucket: 'notepad-2d87a.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIO2nyp4sFgeqKnm3-6lCzTHnHLWnr9yI',
    appId: '1:772902708850:web:53321f26eb07d984e784eb',
    messagingSenderId: '772902708850',
    projectId: 'notepad-2d87a',
    authDomain: 'notepad-2d87a.firebaseapp.com',
    storageBucket: 'notepad-2d87a.firebasestorage.app',
    measurementId: 'G-GPKNNRSP95',
  );
}
